version: '3.1'
services:
  db:
    image: postgres:16.1
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
  adminer:
    image: adminer
    restart: always
    ports:
      - "80:8080"